{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ $.Values.global.eureka.url }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ $.Values.global.kafka.bootstrapServers }}
            - name: ZIPKIN_BASE_URL
              value: {{ $.Values.global.zipkin.url }}
{{- if $svc.db }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.{{ $.Values.namespace }}.svc.cluster.local:{{ $.Values.global.postgres.port }}/{{ $svc.db }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ $.Values.global.postgres.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ $.Values.global.postgres.password }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      nodePort: {{ $svc.nodePort }}
{{- end }}
{{- end }}

